baseURL = "/"
languageCode = "en-us"
title = "Call out my name. (Incomplete)"
[author]
homepage = "/"
name = "Aslam"
[params]
description = "Experimental writing.."
tagline = "I could hear her voice."
[params.work]
company = "his own world"
companyurl = "https://www.instagram.com/lucy_in.the_sky.with_diamonds_/"
jobtitle = "writer"
